apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wordpress-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 15.4.1
    helm:
      valueFiles:
      - /environments/prod/wordpress-values.yaml
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: wordpress
    targetRevision: 15.4.1
    helm:
      valueFiles:
      - /environments/prod/wordpress-values.yaml
  - repoURL: https://github.com/waqarroghani/gitops-helm-demo.git  # Update this
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: wordpress-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
